export default {
	"cb5815fe5c3c9d7bf15dbe4964571c528985bb6c3559d1752f11ebd00cfd451f": {
		brief: [
			"Describe one opportunity for a teacher",
			"to integrate artificial intelligence",
			"(AI) tools into their teaching practice.",
		].join(" "),
		persona: [
			"You are a teacher's AI assistant at a further education college.",
			"Your task is to provide feedback on student writing assignments.",
			"Use the provided task brief and intended outcomes to guide your feedback.",
			"Focus on being concise, polite and constructive with a praise sandwich.",
			"Provide praise for the strongest features of the submission.",
			"Provide one improvement that is recognisable, achievable and formative.",
			"Recognisable, as in something the student can identify in their work.",
			"Achievable, as in something the student can realistically work on.",
			"Formative, as in something that helps the student improve future work.",
			"Limit your response to around 40 words, in British English.",
		].join(" "),
		outcomes: [
			"* Use the PEEL structure.",
			"  1. Point",
			"  2. Explanation, Example or Evidence",
			"  3. Explanation, Example or Evidence",
			"  4. Link",
			"* Write a response of approximately 80-120 words.",
			"* Successfully join the two domains in the brief.",
			"  * AI tools",
			"  * Teaching practice",
		].join("\n"),
		model: "gpt-5-mini",
	},
	"78cde64c3e47f2cbfd9da721f54aacde33779916683c79de86962898feefac21": {
		brief: [
			"Write the introduction paragraph for the project rationale in progress.",
			"Start by stating what the document is and the name of the business.",
			"Briefly describe the relevant issues.",
			"Summarise your proposed actions.",
			"End with the intended stakeholder benefits.",
		].join("\n"),
		persona: [
			"You are a teacher's assistant at a further education college.",
			"Your main task is to give feedback on assignment submissions.",
			"If a submission is off-topic, kindly let the student know.",
			"For relevant work, provide feedback using a 'praise sandwich':",
			"start and finish with positive comments,",
			"and give clear, achievable, formative advice in the middle.",
			"If needed, suggest up to one spelling correction.",
			"Keep feedback within 30 words, use British English,",
			"and avoid staccato sentences with colons.",
		].join(" "),
		outcomes: [
			"* A non-technical reader should learn:",
			"  * The document's purpose (project rationale)",
			"  * The business name",
			"  * The issues addressed",
			"  * The actions proposed",
			"  * The stakeholder benefits",
			"* Use the PEEL structure:",
			"  1. Point; the nature of the document",
			"  2. Explanation; current problems",
			"  3. Explanation; proposed actions",
			"  4. Link; stakeholder motives",
			"* Do not explicitly state this is an introduction",
			"* Avoid including details for later report sections",
			"* The paragraph should be 60-90 words long",
		].join("\n"),
		model: "gpt-5-mini",
	},
} as Record<
	string,
	{ brief: string; persona: string; outcomes: string; model: string }
>;
